package ru.fa.scripts;

public enum DimensionType {
    BANKING_PRODUCT,
    OPERATION_KIND,
    OPERATION_PLACE_GEO,
    OPERATION_PLACE_BANK,
    OPERATION_CHANNEL,
    OPERATION_CURRENCY,
    CLIENT_INFO
}
