package ru.fa.scripts;

public enum ValueSubType {
    TRANSACTION_FEE_WITHIN_LIMIT,
    TRANSACTION_FEE_ABOVE_LIMIT,
    TRANSACTION_LIMIT_PER_MONTH,
    TRANSACTION_LIMIT_PER_DAY,
    TRANSACTION_LIMIT_PER_OPERATION,
    TARIFF,
    REQUIRED_DOCUMENTS,
    CHANNELS,
    INFORMATION,
    CREDIT_LIMIT,
    PERIOD
}
